config/routes.rb
Rails.application.routes.draw do
  root 'depts#index'
  
  resources :depts do
    resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dept.rb
class Dept < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :dept
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception  
end

app/controllers/depts_controller.rb
class DeptsController < ApplicationController
  before_action :set_dept, only: [:show, :update, :edit, :destroy]

  def index
    @depts = Dept.all
  end

  def show
    # render :show
  end

  def new
    @dept = Dept.new
    render partial: 'form'
  end

  def create
    @dept = Dept.new(dept_params)

    if @dept.save
      redirect_to depts_path
    else
      render :new
    end
  end

  def edit
    render partial: 'form'
  end

  def update
    if @dept.update
      redirect_to @dept
    else
      render :edit
    end
  end

  def destroy
    @dept.destroy
    redirect_to depts_path
  end


  private

  def set_dept
    @dept = Dept.find(params[:id])
  end

  def dept_params
    params.require(:dept).permit(:name)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_dept
  before_action :set_items, only: [:show, :edit, :update, :destroy]

  def index
    @items = @dept.items
  end

  def show
  end

  def new
    @item = @dept.items.new
    render partial: 'form'
  end

  def create
    @item = @dept.items.new(item_params)

    if @item.save
      redirect_to [@dept, @item]
    else
      render :new
    end
  end

  def edit
    render partial: 'form'
  end

  def update
   if @item.update(item_params)
    redirect_to [@dept, @item]
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to dept_items_path
  end

  private

  def set_dept
    @dept = Dept.find(params[:dept_id])
  end

  def set_items
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :price, :details, :availability)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/depts_helper.rb
module DeptsHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/depts/_form.html.erb
<h1><%= @dept.id ? 'Edit Department' : 'Create Department' %></h1>
<hr />
<%= form_for @dept do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/depts/edit.html.erb
<h1>Depts#edit</h1>
<p>Find me in app/views/depts/edit.html.erb</p>

app/views/depts/index.html.erb
<h1>Department Store</h1>
<hr />
<h5>Click a Department To View Items</h5>
<%= link_to 'Create a New Department', new_dept_path %>
<ul>
  <% @depts.each do |dept| %>
    <li><%= link_to dept.name, dept %></li>
  <% end %>
</ul>

app/views/depts/new.html.erb
<h1>Depts#new</h1>
<p>Find me in app/views/depts/new.html.erb</p>

app/views/depts/show.html.erb
<h1><%= @dept.name %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View Items', dept_items_path(@dept) %>
<br />
<%= link_to 'Edit Department', edit_dept_path(@dept) %>
<br />
<%= link_to 'Delete Department', @dept, method: :delete %>

app/views/item/_form.html.erb
<h1><%= @item.id ? 'Edit Item' : 'Create Item' %></h1>
<hr />
<%= form_for [@dept, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :price %>
  <%= f.text_field :price, required: true %>
  <br />
  <%= f.label :details %>
  <%= f.text_area :details, required: true %>
  <br />
  <%= f.label :availability %>
  <%= f.check_box :availability %>
  <%= f.submit %>
<% end %>

app/views/items/_form.html.erb
<h1><%= @item.id ? 'Edit Item' : 'Create Item' %></h1>
<hr />
<%= form_for [@dept, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :price %>
  <%= f.text_field :price, required: true %>
  <br />
  <%= f.label :details %>
  <%= f.text_area :details, required: true %>
  <br />
  <%= f.label :availabilty %>
  <%= f.check_box :availabilty %>
  <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h4>Click an Item To View Content</h4>
<%= link_to 'Create a new item', new_dept_item_path(@dept) %>
<ul>
  <% @items.each do |item| %>
    <li><%= link_to item.name, [@dept, item] %></li>
  <% end %>
</ul>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1><%= @dept.name %> - <%= @item.name %></h1>
<hr />
<p>$<%= @item.price %></p>
<br />
<p><%= @item.details %></p>
<br />
<%= link_to 'Edit Item', edit_dept_item_path([@dept, @item]) %>
<br />
<%= link_to 'Delete Item', [@dept, @item], method: :delete %>
<br />
<%= link_to 'Back To Items', dept_items_path(@dept) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Department Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>